# Generated by Django 5.0.4 on 2024-04-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invertor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('pv1_input_power', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Входная мощность pv1 (Вт) за 1 сек')),
                ('pv1_voltage', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Напряжение pv1 (В) за 1 сек')),
                ('pv1_current', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Ток pv1 (А) за 1 сек')),
                ('pv2_input_power', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Входная мощность pv2 (Вт) за 1 сек')),
                ('pv2_voltage', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Напряжение pv2 (В) за 1 сек')),
                ('pv2_current', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Ток pv2 (А) за 1 сек')),
                ('grid_voltage', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Напряжение сети (В) за 1 сек')),
                ('grid_current', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Ток сети (А) за 1 сек')),
                ('grid_frequency', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Частота сети (Гц) за 1 сек')),
                ('output_power', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Выходная мощность (Вт) за 1 сек')),
                ('energy_today', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Энергия сегодня (кВт*ч) за 1 сек')),
                ('energy_total', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Общая энергия (кВт*ч) за 1 сек')),
            ],
            options={
                'verbose_name': 'Данные с инвертора',
                'verbose_name_plural': 'Данные с инвертора',
            },
        ),
        migrations.CreateModel(
            name='MeteoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('TA', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Среднее значение температуры за 1 минуту, C')),
                ('DP', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Точка росы, C')),
                ('WC', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Охлаждение ветром , C')),
                ('RH', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Относительная влажность, %')),
                ('PA', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Атмосферное давление, mm Hg')),
                ('PR', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Количество жидких осадков мгновенное значение, мм')),
                ('PR1H', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Количество жидких осадков сумма за 1 час, мм')),
                ('PR24H', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Количество жидких осадков сумма за сутки, мм')),
                ('SR_1M', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Данные от CMP6 установленного параллельно относительно поверхности земли (Вт/м²) среднее значение за 1 минуту')),
                ('SR_1D', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Данные от CMP6 установленного параллельно относительно поверхности земли (Вт/м²) среднее значение за 24 часа')),
                ('SR_45_1M', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Данные от CMP6 установленного 45 градусов относительно поверхности земли (Вт/м²) среднее значение за 1 минуту')),
                ('SR_45_1D', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Данные от CMP6 установленного 45 градусов относительно поверхности земли (Вт/м²) среднее значение за 24 часа')),
                ('SD_1H', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Данные от CMP6 установленного 45 градусов относительно поверхности земли (Вт/м²) суммарное значение за 1 час')),
                ('SD_1D', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Данные от CMP6 установленного 45 градусов относительно поверхности земли (Вт/м²) суммарное значение за 24 часа')),
                ('SD_45_1H', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Данные от CMP6 установленного 45 градусов относительно поверхности земли (Вт/м²) суммарное значение за 1 час')),
                ('SD_45_1D', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Данные от CMP6 установленного 45 градусов относительно поверхности земли (Вт/м²) суммарное значение за 24 часа')),
            ],
            options={
                'verbose_name': 'Данные с метеостанции',
                'verbose_name_plural': 'Данные с метеостанции',
            },
        ),
        migrations.CreateModel(
            name='WindData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('WS1AVG', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Cкорость ветра (м/с) за 3 сек')),
                ('WD1AVG', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Направление ветра (град) за 3 сек')),
                ('WS1MIN2', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Cкорость ветра (м/с) минимальное значение за 2 минуты')),
                ('WS1AVG2', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Cкорость ветра (м/с) среднее значение за 2 минуты')),
                ('WS1MAX2', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Cкорость ветра (м/с) максимальное значение за 2 минуты')),
                ('WD1MIN2', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Направление ветра (град) минимальное значение за 2 минуты')),
                ('WD1AVG2', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Направление ветра (град) среднее значение за 2 минуты')),
                ('WD1MAX2', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Направление ветра (град) максимальное значение за 2 минуты')),
                ('WS1MIN10', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Cкорость ветра (м/с) минимальное значение за 10 минут')),
                ('WS1AVG10', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Скорость ветра (м/с) среднее значение за 10 минут')),
                ('WS1MAX10', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Скорость ветра (м/с) максимальное значение за 2 минуты')),
                ('WD1MIN10', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Направление ветра (град) минимальное значение за 10 минут')),
                ('WD1AVG10', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Направление ветра (град) среднее значение за 10 минут')),
                ('WD1MAX10', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Направление ветра (град) максимальное значение за 10 минут')),
            ],
            options={
                'verbose_name': 'Данные с ветряного модуля',
                'verbose_name_plural': 'Данные с ветряного модуля',
            },
        ),
    ]
